apiVersion: v1
data:
  create-db.sql: |-
    CREATE DATABASE rides;
    CREATE DATABASE booking;
    CREATE DATABASE users;
    CREATE DATABASE notifications;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: database
  name: database-cm1
