services:
  api:
    build: .
    container_name: api
    ports:
      - "80:5000"
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file: .env
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
